[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "angular", "--stdin-filepath=file.html"]}
auto-format = true
language-servers = ["vscode-html-language-server", "tailwindcss-ls", "angular", "typos"]

[[language]]
name = "svelte"
auto-format = true
language-servers = ["svelteserver", "tailwindcss-ls", "typos"]
